//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class library : DbContext
    {
        public library()
            : base("name=library")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Authors> Authors { get; set; }
        public DbSet<Books> Books { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Departments> Departments { get; set; }
        public DbSet<Faculties> Faculties { get; set; }
        public DbSet<Groups> Groups { get; set; }
        public DbSet<Libs> Libs { get; set; }
        public DbSet<Press> Press { get; set; }
        public DbSet<S_Cards> S_Cards { get; set; }
        public DbSet<Students> Students { get; set; }
        public DbSet<T_Cards> T_Cards { get; set; }
        public DbSet<Teachers> Teachers { get; set; }
        public DbSet<Themes> Themes { get; set; }
    }
}
