//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Cards
    {
        public int Id { get; set; }
        public int Id_Student { get; set; }
        public int Id_Book { get; set; }
        public System.DateTime DateOut { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public int Id_Lib { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Libs Libs { get; set; }
        public virtual Students Students { get; set; }
    }
}
