//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReversEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public int Id_dep { get; set; }
        public string Name { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
